---
- import_tasks: logging/main.yml
  tags: ['role::bootstrap:logging']

- import_tasks: packages/main.yml
  tags: ['role::bootstrap:packages']

- import_tasks: consul/main.yml
  tags: ['role::bootstrap:consul']
  when: bootstrap__consul_enabled

- import_tasks: users/main.yml
  tags: ['role::bootstrap:users']
