---
- import_tasks: logging/main.yml
  tags: ['role::bootstrap:logging']

- import_tasks: packages/main.yml
  tags: ['role::bootstrap:packages']

- import_tasks: users/main.yml
  tags: ['role::bootstrap:users']
