---
- import_tasks: ansible.yml
  tags: ['role::bootstrap:ansible']

- import_tasks: logging/main.yml
  tags: ['role::bootstrap:logging']

- import_tasks: packages/main.yml
  tags: ['role::bootstrap:packages']

- import_tasks: consul/main.yml
  tags: ['role::bootstrap:consul']
  when: bootstrap__consul_enabled

- import_tasks: users/main.yml
  tags: ['role::bootstrap:users']

- import_tasks: openssh/main.yml
  tags: ['role::bootstrap:openssh']

- import_role: name=infra-role-wireguard
  tags: ['role::wireguard']
  when: bootstrap__wireguard_enabled|bool
