---
- name: '{{ user.name }} - Create user'
  tags: ['role::bootstrap:users']
  win_user:
    name: '{{ user.name }}'
    groups: '{{ bootstrap__default_groups + user.groups }}'
    profile: 'C:\Users\{{ user.name }}'
    # We set garbage since we use SSH keys anyway
    password: '{{ ansible_date_time.epoch | password_hash("sha512") }}'

- name: '{{ user.name }} - Create SSH config directory'
  tags: ['role::bootstrap:users']
  win_file:
    path: 'C:\Users\{{ user.name }}\.ssh'
    state: 'directory'

- name: '{{ user.name }} - Copy over SSH public key from entry'
  tags: ['role::bootstrap:users']
  win_copy:
    dest: '{{ role_path }}/files/keys/{{ user.name }}.pub'
    content: '{{ user.key }}'
  when: user.key is defined

- name: '{{ user.name }} - Copy over SSH public key from file'
  tags: ['role::bootstrap:users']
  win_copy:
    dest: 'C:\Users\{{ user.name }}\.ssh\authorized_keys'
    src: '{{ role_path }}/files/keys/{{ user.name }}.pub'
  when: user.key is not defined
