---
- name: Install scoop package manager
  win_shell: 'Invoke-Expression (New-Object System.Net.WebClient).DownloadString("https://get.scoop.sh")'

- name: Install base packages
  win_shell: 'scoop install --global {{ bootstrap__base_packages | join(" ") }}'
