---
- name: Check if scoop is installed
  win_shell: 'Get-Command scoop'
  ignore_errors: yes
  no_log: true
  register: scoop_check

- name: Install scoop package manager
  win_shell: 'Invoke-Expression (New-Object System.Net.WebClient).DownloadString("https://get.scoop.sh")'
  when: scoop_check.failed

- name: Install base packages
  win_shell: 'scoop install --global {{ bootstrap__base_packages | join(" ") }}'
