---
- name: Install scoop package manager
  tags: ['role::bootstrap:packages']
  win_shell: |
    Invoke-Expression (
      New-Object System.Net.WebClient
    ).DownloadString("https://get.scoop.sh")

- win_shell: '$env:UserName'
  register: debug_output
- debug: var=debug_output

- name: Add extras scoop bucket
  tags: ['role::bootstrap:packages']
  win_shell: 'scoop bucket add extras'

- name: Install base packages
  tags: ['role::bootstrap:packages']
  win_shell: 'scoop install --global {{ bootstrap__base_packages | join(" ") }}'
